[package]
name = "ceramic"
version = "0.1.0"
authors = ["cryscan <cryscan@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.8"
ron = "0.5.1"
serde = {version = "1.0.104", features = ["derive"]}
amethyst = {version = "0.13.2", features = ["vulkan", "nightly"]}